name: build the image
on:
  push:
    branches:
      - main

jobs:
  docker-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag from branch
        id: tag
        run: |
          TAG=$(echo "${GITHUB_REF_NAME}" | tr '/' '-')
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - uses: int128/kaniko-action@v1.7.0
        with:
          tags: ghcr.io/charafzellou/blockchain-ops-kata/application:${{ steps.tag.outputs.tag }}
          context: app
          file: app/Dockerfile
          push: true